import {
  PlanningAgent,
  PlanningSite,
  PlanningSlotDefinition,
} from "./planning.types"

export const planningSlots: PlanningSlotDefinition[] = [
  { key: "matin", label: "Matin", time: "07h20 - 08h35" },
  { key: "midi", label: "Midi", time: "11h20 - 13h20" },
  { key: "atsem", label: "ATSEM", time: "08h00 - 18h00" },
  { key: "soir", label: "Soir", time: "16h20 - 19h00" },
]

export const planningSites: PlanningSite[] = [
  { id: "gentillerie", name: "La Gentillerie", status: "ok" },
  { id: "legatelois", name: "Legatelois", status: "warning" },
  { id: "belair", name: "Bel Air", status: "danger" },
]

export const planningAgents: PlanningAgent[] = [
  {
    id: "a1",
    firstName: "Alexandra",
    lastName: "L.",
    position: "ATSEM",
    siteId: "gentillerie",
    slot: "matin",
    start: "07h20",
    end: "08h35",
    status: "present",
  },
  {
    id: "a2",
    firstName: "Patricia",
    lastName: "H.",
    position: "ATSEM",
    siteId: "gentillerie",
    slot: "matin",
    start: "07h20",
    end: "08h35",
    status: "present",
  },
  {
    id: "a3",
    firstName: "Clémence",
    lastName: "G.",
    position: "Animatrice",
    siteId: "gentillerie",
    slot: "midi",
    start: "11h20",
    end: "13h20",
    status: "present",
  },
  {
    id: "a4",
    firstName: "Julie",
    lastName: "B.",
    position: "Animatrice",
    siteId: "gentillerie",
    slot: "midi",
    start: "11h20",
    end: "13h20",
    status: "present",
  },
  {
    id: "a5",
    firstName: "Céline",
    lastName: "G.",
    position: "ATSEM",
    siteId: "gentillerie",
    slot: "atsem",
    start: "08h00",
    end: "18h00",
    status: "present",
  },
  {
    id: "a6",
    firstName: "Jordan",
    lastName: "L.",
    position: "Animateur",
    siteId: "gentillerie",
    slot: "soir",
    start: "16h20",
    end: "19h00",
    status: "present",
  },
  {
    id: "a7",
    firstName: "Johan",
    lastName: "C.",
    position: "Animateur",
    siteId: "gentillerie",
    slot: "soir",
    start: "16h20",
    end: "19h00",
    status: "present",
  },
  {
    id: "a8",
    firstName: "Caroline",
    lastName: "R.",
    position: "Animatrice",
    siteId: "legatelois",
    slot: "matin",
    start: "07h20",
    end: "08h35",
    status: "present",
  },
  {
    id: "a9",
    firstName: "Agent",
    lastName: "absent",
    position: "Absence",
    siteId: "belair",
    slot: "soir",
    start: "16h20",
    end: "19h00",
    status: "absence",
  },
]